src/main/java/org/overture/ego/controller/AuthController.java, src/main/java/org/overture/ego/model/enums/UserStatus.java, src/main/java/org/overture/ego/security/SecureAuthorizationManager.java
API requests are rejected by secure filter if the user is in Pending state.
Updated SecureAuthorizationManager to use constants instead of String literals, and used the "demo" config value to assign Approved status to new users.
https://github.com/overture-stack/ego/issues/19
=> [EGO-19] Demo User registrations now Approved by default

src/main/java/org/overture/ego/controller/ApplicationController.java, src/main/java/org/overture/ego/controller/GroupController.java, src/main/java/org/overture/ego/controller/UserController.java, src/main/java/org/overture/ego/model/dto/PageDTO.java
To keep with the existing API interface that was defined before inclusion of Spring Pagination. PageDTO provides the specific interface, and is built directly from the Spring Page results pro
vided from the services/repositories.
=> PageDTO Added - Spring Page replaced in all Controllers

src/main/java/org/overture/ego/config/WebRequestConfig.java, src/main/java/org/overture/ego/controller/ApplicationController.java, src/main/java/org/overture/ego/controller/GroupController.java, src/main/java/org/overture/ego/controller/UserController.java, src/main/java/org/overture/ego/controller/resolver/PageableResolver.java, src/main/java/org/overture/ego/repository/ApplicationRepository.java, src/main/java/org/overture/ego/repository/UserRepository.java, src/main/java/org/overture/ego/repository/queryspecification/SpecificationBase.java, src/main/java/org/overture/ego/service/ApplicationService.java, src/main/java/org/overture/ego/service/GroupService.java, src/main/java/org/overture/ego/service/UserService.java
Updated pageable fields as needed by front end
Added documentation for pageable fields in Swagger
Added status query support in rest endpoints
=> Updated pageable fields and support for status filtering

README.md, src/main/java/org/overture/ego/token/TokenUserInfo.java
JWT was missing:
- createdAt
- lastLogin
- preferredLanguage
Updated README to show camel case fields
=> JWT include all user fields, Update Docs to match

src/main/resources/scripts/env_template.sh, src/main/resources/scripts/start-server.sh
Also updated start script to use the new env vars.
=> DB Host and Port added to env template

src/main/java/org/overture/ego/config/WebRequestConfig.java, src/main/java/org/overture/ego/controller/ApplicationController.java, src/main/java/org/overture/ego/controller/GroupController.java, src/main/java/org/overture/ego/controller/UserController.java, src/main/java/org/overture/ego/controller/resolver/FilterResolver.java, src/main/java/org/overture/ego/model/entity/Application.java, src/main/java/org/overture/ego/model/entity/Group.java, src/main/java/org/overture/ego/model/entity/User.java, src/main/java/org/overture/ego/model/enums/Fields.java, src/main/java/org/overture/ego/model/search/Filters.java, src/main/java/org/overture/ego/model/search/SearchFilter.java, src/main/java/org/overture/ego/repository/queryspecification/ApplicationSpecification.java, src/main/java/org/overture/ego/repository/queryspecification/GroupSpecification.java, src/main/java/org/overture/ego/repository/queryspecification/SpecificationBase.java, src/main/java/org/overture/ego/repository/queryspecification/UserSpecification.java, src/main/java/org/overture/ego/service/ApplicationService.java, src/main/java/org/overture/ego/service/GroupService.java, src/main/java/org/overture/ego/service/UserService.java, src/main/java/org/overture/ego/utils/FieldUtils.java, src/main/java/org/overture/ego/utils/QueryUtils.java
Added support for filtering by entity fields. User can apply filters to any Endpoint that returns a Page . Filters are applied as query parameters in the format: fieldName=fieldValue
=> Added support for filtering results by any field of the entity

src/main/java/org/overture/ego/model/entity/User.java, src/main/java/org/overture/ego/service/UserService.java
Fix situation where duplicate group/application additions to a user could cause issues. This is already protected against in the UI, but makes EGO enforce no duplicates as well.
=> User.groups and User.applicaitons are now Sets

src/main/java/org/overture/ego/model/entity/User.java, src/main/java/org/overture/ego/service/UserService.java
https://github.com/overture-stack/ego/issues/74
=> UserService.update merges existing user, does not erase groups and apps

src/main/java/org/overture/ego/service/UserService.java
Initialize all user fields in the DB when created.
https://github.com/overture-stack/ego/issues/66
=> UserService.create sets createdAt and name fields

src/main/java/org/overture/ego/service/UserService.java, src/main/java/org/overture/ego/token/TokenService.java, src/main/resources/application.yml
Implemented check for user role case sensitivity
=> Fix User role update

Dockerfile
Removed nginx related steps from DockerFile. We'll add those later once we figure out exact steps for CI/CD.
=> Removed nginx related config from DockerFile

Jenkinsfile
- Added the new Jenkinsfile
- Migrated state files into different s3 bucket
- Migrated deployment to use module
=> 👷 Modified jenkins file

src/main/java/org/overture/ego/config/SecureServerConfig.java, src/main/java/org/overture/ego/model/entity/User.java, src/main/java/org/overture/ego/security/JWTAuthorizationFilter.java, src/main/java/org/overture/ego/token/TokenService.java
* Fixed a bug that got introduced after refactor - Conversion user roles
* Explicitly define Public Endpoints
=> 🐛fix: Token Verification and Public Endpoints Definition

README.md
adding progress bar to ego readme
=> Kcullion patch 1

src/main/java/org/overture/ego/service/UserService.java, src/main/resources/application.yml, src/test/java/org/overture/ego/service/UserServiceTest.java
```
default:
user:
role: USER
status: Approved
```
=> Default user attributes now configurable

src/main/java/org/overture/ego/controller/GroupController.java, src/main/java/org/overture/ego/controller/ResourceController.java, src/main/java/org/overture/ego/controller/UserController.java, src/main/java/org/overture/ego/model/entity/AclEntity.java, src/main/java/org/overture/ego/model/entity/AclGroupPermission.java, src/main/java/org/overture/ego/model/entity/AclOwnerEntity.java, src/main/java/org/overture/ego/model/entity/AclPermission.java, src/main/java/org/overture/ego/model/entity/AclUserPermission.java, src/main/java/org/overture/ego/model/entity/Group.java, src/main/java/org/overture/ego/model/entity/User.java, src/main/java/org/overture/ego/model/enums/AclMask.java, src/main/java/org/overture/ego/repository/AclEntityRepository.java, src/main/java/org/overture/ego/repository/AclGroupPermissionRepository.java, src/main/java/org/overture/ego/repository/AclUserPermissionRepository.java, src/main/java/org/overture/ego/repository/queryspecification/AclEntitySpecification.java, src/main/java/org/overture/ego/repository/queryspecification/AclPermissionSpecification.java, src/main/java/org/overture/ego/service/AclEntityService.java, src/main/java/org/overture/ego/service/GroupService.java, src/main/java/org/overture/ego/service/PermissionService.java, src/main/java/org/overture/ego/service/UserService.java, src/main/java/org/overture/ego/utils/AclPermissionUtils.java, src/test/java/org/overture/ego/model/enums/AclMaskTest.java, src/test/java/org/overture/ego/service/AclEntityServiceTest.java, src/test/java/org/overture/ego/utils/EntityGenerator.java
Reverts overture-stack/ego#146
=> Revert "Enhancement: Renamed Acl to Policy"

src/main/java/org/overture/ego/controller/AuthController.java, src/main/java/org/overture/ego/controller/GroupController.java, src/main/java/org/overture/ego/controller/UserController.java, src/main/java/org/overture/ego/service/GroupService.java, src/main/java/org/overture/ego/service/UserService.java
This PR is done now. :-) 
We need a separate ticket to make the authentication tokens use JSON.
=> Feature/make ego return proper json and follow rest api rules#120#123#121#59

src/main/java/org/overture/ego/model/entity/Application.java
https://github.com/overture-stack/ego-ui/issues/5
=> Fix application status visibility

src/main/java/bio/overture/ego/model/entity/Group.java, src/main/java/bio/overture/ego/service/GroupService.java
Makes the update method return a new group rather than being a void method.
=> Bug fix for updating fields on a group.

pom.xml, src/main/java/bio/overture/ego/controller/AuthController.java, src/main/java/bio/overture/ego/provider/linkedin/LinkedInOAuthService.java, src/main/java/bio/overture/ego/service/OAuthService.java, src/main/resources/application.yml
=> Add linkedin login

src/main/java/bio/overture/ego/config/SwaggerConfig.java, src/main/java/bio/overture/ego/model/entity/User.java, src/main/java/bio/overture/ego/service/AbstractPermissionService.java, src/main/java/bio/overture/ego/service/GroupPermissionService.java, src/main/java/bio/overture/ego/service/GroupService.java, src/main/java/bio/overture/ego/service/UserPermissionService.java, src/main/java/bio/overture/ego/service/UserService.java, src/main/resources/application.yml, src/test/java/bio/overture/ego/controller/AbstractControllerTest.java, src/test/java/bio/overture/ego/controller/AbstractPermissionControllerTest.java, src/test/java/bio/overture/ego/controller/ApplicationControllerTest.java, src/test/java/bio/overture/ego/controller/GroupControllerTest.java, src/test/java/bio/overture/ego/controller/GroupPermissionControllerTest.java, src/test/java/bio/overture/ego/controller/MappingSanityTest.java, src/test/java/bio/overture/ego/controller/PolicyControllerTest.java, src/test/java/bio/overture/ego/controller/UserControllerTest.java, src/test/java/bio/overture/ego/controller/UserPermissionControllerTest.java, src/test/java/bio/overture/ego/service/GroupsServiceTest.java, src/test/java/bio/overture/ego/service/PermissionServiceTest.java
Typos, renames and small refactors that did not make the #246  and #257 PRs
=> Permissions typos

src/main/java/bio/overture/ego/controller/ApplicationController.java, src/main/java/bio/overture/ego/controller/GroupController.java, src/main/java/bio/overture/ego/controller/PolicyController.java, src/main/java/bio/overture/ego/controller/TokenController.java, src/main/java/bio/overture/ego/controller/UserController.java, src/main/java/bio/overture/ego/model/dto/TokenResponse.java, src/main/java/bio/overture/ego/reactor/receiver/UserReceiver.java, src/main/java/bio/overture/ego/service/AbstractPermissionService.java, src/main/java/bio/overture/ego/service/ApplicationService.java, src/main/java/bio/overture/ego/service/GroupService.java, src/main/java/bio/overture/ego/service/PolicyService.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/java/bio/overture/ego/service/TokenStoreService.java, src/main/java/bio/overture/ego/service/UserService.java, src/test/java/bio/overture/ego/selenium/driver/WebDriverFactory.java, src/test/java/bio/overture/ego/service/ApplicationServiceTest.java, src/test/java/bio/overture/ego/service/GroupsServiceTest.java, src/test/java/bio/overture/ego/service/PolicyServiceTest.java, src/test/java/bio/overture/ego/service/UserServiceTest.java, src/test/java/bio/overture/ego/token/LastloginTest.java, src/test/java/bio/overture/ego/token/ListTokenTest.java, src/test/java/bio/overture/ego/token/TokenServiceTest.java
=> refactor: Converted all String ids to UUID in all controllers

pom.xml, src/test/java/bio/overture/ego/selenium/LoadAdminUITest.java
Addresses a vulnerability. 
Selenium tests passed locally in addition to unit tests.
=> upgrade spring security oauth2

src/main/java/bio/overture/ego/repository/TokenStoreRepository.java, src/main/java/bio/overture/ego/service/TokenStoreService.java, src/test/java/bio/overture/ego/controller/TokenControllerTest.java, src/test/java/bio/overture/ego/utils/EntityGenerator.java
=> Revoke duplicated tokens when an new token is created

src/main/java/bio/overture/ego/repository/queryspecification/builder/AbstractSpecificationBuilder.java, src/main/java/bio/overture/ego/service/AbstractBaseService.java, src/main/java/bio/overture/ego/service/BaseService.java, src/main/java/bio/overture/ego/service/UserService.java
add a generic service call to list entities and get many while also defining the fetch plan at runtime
=> ego-dynamically-loaded-find-all

src/main/java/bio/overture/ego/model/entity/User.java, src/main/java/bio/overture/ego/model/enums/LombokFields.java, src/main/java/bio/overture/ego/repository/queryspecification/builder/TokenSpecificationBuilder.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/java/bio/overture/ego/service/TokenStoreService.java
=> excluded userApplications from toString method for User

src/main/java/bio/overture/ego/model/entity/User.java, src/main/proto/Ego.proto
Changing lists of Boxed variables to list of primitives.
=> Change user proto to return list of strings

src/main/java/bio/overture/ego/grpc/GrpcServer.java, src/main/java/bio/overture/ego/grpc/ProtoUtils.java, src/main/java/bio/overture/ego/grpc/interceptor/ApplicationAuthInterceptor.java, src/main/java/bio/overture/ego/grpc/service/UserServiceGrpcImpl.java, src/main/java/bio/overture/ego/model/entity/User.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/java/bio/overture/ego/utils/TypeUtils.java, src/main/proto/Ego.proto, src/test/java/bio/overture/ego/grpc/ProtoUtilsTest.java, src/test/java/bio/overture/ego/grpc/service/UserServiceGrpcAuthTest.java, src/test/java/bio/overture/ego/grpc/service/UserServiceGrpcTest.java, src/test/java/bio/overture/ego/service/UserServiceTest.java
Applied the rules:
GetUser: Is an App || is Admin || is a user requesting their own user data
ListUser: Is an App || is Admin
=> Add per service auth requirements to gRPC User Service

src/main/java/bio/overture/ego/model/dto/CreateUserRequest.java, src/main/java/bio/overture/ego/model/entity/User.java, src/main/resources/flyway/sql/V1_13__fname_lname_not_null_constraints.sql, src/test/java/bio/overture/ego/controller/UserControllerTest.java, src/test/java/bio/overture/ego/grpc/service/UserServiceGrpcAuthTest.java
=> Ego 356 nonull fname lname

src/main/java/bio/overture/ego/controller/ApiKeyController.java, src/main/java/bio/overture/ego/model/dto/TokenResponse.java, src/main/java/bio/overture/ego/service/TokenService.java
Restores old token endpoints as deprecated with correct responses.
=> 2.9 deprecation

src/main/java/bio/overture/ego/controller/AuthController.java, src/main/java/bio/overture/ego/model/domain/RefreshContext.java, src/main/java/bio/overture/ego/model/entity/RefreshToken.java, src/main/java/bio/overture/ego/model/entity/User.java, src/main/java/bio/overture/ego/model/enums/JavaFields.java, src/main/java/bio/overture/ego/model/exceptions/UnauthorizedException.java, src/main/java/bio/overture/ego/service/RefreshContextService.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/resources/application.yml, src/test/java/bio/overture/ego/model/domain/RefreshContextTest.java, src/test/java/bio/overture/ego/service/RefreshContextServiceTest.java, src/test/java/bio/overture/ego/utils/EntityGenerator.java
- cleans up logic for expired refresh token
- cleans up comments
=> 394 implement refresh token

src/main/java/bio/overture/ego/config/SwaggerConfig.java, src/main/java/bio/overture/ego/controller/AuthController.java, src/main/java/bio/overture/ego/utils/SwaggerConstants.java
This method avoids that ugly new entry in swagger, while just proxying the postAccessToken request
=> rtisma patch

src/main/java/bio/overture/ego/service/TokenService.java, src/test/java/bio/overture/ego/controller/AppJWTTest.java, src/test/java/bio/overture/ego/controller/UserJwtTest.java
Related to #493 
Still a WIP, needs tests
=> ego-493-update-explicit-scopes

src/main/java/bio/overture/ego/config/InitializationConfig.java, src/main/java/bio/overture/ego/event/token/InitApplicationListener.java, src/main/java/bio/overture/ego/model/entity/InitTripWire.java, src/main/java/bio/overture/ego/model/enums/SqlFields.java, src/main/java/bio/overture/ego/model/enums/Tables.java, src/main/java/bio/overture/ego/repository/InitTripWireRepository.java, src/main/java/bio/overture/ego/service/InitializationService.java, src/main/resources/application.yml, src/main/resources/flyway/sql/V1_18__ego_init.sql, src/test/java/bio/overture/ego/service/initialization/InitializationEventTest.java, src/test/java/bio/overture/ego/service/initialization/InitializationServiceTest.java
=> Ego Initialization

src/main/java/bio/overture/ego/model/dto/LinkedinEmail.java, src/main/java/bio/overture/ego/model/dto/LinkedinEmailResponse.java, src/main/java/bio/overture/ego/model/enums/LinkedinContactType.java, src/main/java/bio/overture/ego/security/OAuth2SsoFilter.java, src/main/java/bio/overture/ego/service/LinkedinService.java, src/main/resources/application.yml
Adds explicit scopes for LinkedIn
Adds handling for new api responses
=> 🐛 547 - Fix scope for linkedin filter

Jenkinsfile, pom.xml, src/main/java/bio/overture/ego/model/dto/LinkedinEmail.java, src/main/java/bio/overture/ego/model/dto/LinkedinEmailResponse.java, src/main/java/bio/overture/ego/model/enums/LinkedinContactType.java, src/main/java/bio/overture/ego/security/OAuth2SsoFilter.java, src/main/java/bio/overture/ego/service/LinkedinService.java, src/main/resources/application.yml
=> 🔖 Rc/4.2.0

src/main/java/bio/overture/ego/model/exceptions/SSOAuthenticationFailureHandler.java, src/test/java/bio/overture/ego/utils/SSOAuthenticationFailureHandlerTest.java
Adds provider type to `access_denied` error response for more informative ui message.
Slight refactor in `SSOAuthenticationFailureHandler` to accommodate this.
Adds test
=> 🚸 569 - Adding providerType to access_denied response

docker-compose.yml, pom.xml, src/main/resources/application.yml
upgrade spring security oauth2 to 2.5.0
upgrade spring security oauth2 autoconfigure 2.4.4
upgrade postgres to 12.6
=> upgrade spring security oauth2 to 2.5.0

docker-compose-all.yml, docker-compose.yml, pom.xml, src/main/java/bio/overture/ego/controller/resolver/PageableResolver.java, src/main/java/bio/overture/ego/grpc/ProtoUtils.java, src/main/java/bio/overture/ego/model/exceptions/ExceptionHandlers.java, src/main/java/bio/overture/ego/utils/IgnoreCaseSortDecorator.java, src/main/resources/application.yml
spring boot 2.5.6
- new syntax for profiles
- profile includes no longer possible
- bootstrap.yaml no longer used, so vault properties moved to application.yaml
- pageable interface changes
=> 612 spring boot & cloud upgrade

pom.xml, src/main/java/bio/overture/ego/controller/AuthController.java, src/main/java/bio/overture/ego/security/OAuth2RequestResolver.java, src/main/java/bio/overture/ego/service/ApplicationService.java, src/main/java/bio/overture/ego/token/CustomTokenEnhancer.java, src/main/java/bio/overture/ego/token/app/AppJWTAccessToken.java, src/test/java/bio/overture/ego/controller/AppJWTTest.java
Couldn't upgrade to latest spring boot (2.6.6) because of springfox issue, will create a ticket to upgrade to latest spring boot with ITCR work
=> Upgrade springboot

README.md, docker-compose-all.yml
Update Docker compose to use latest tag
=> Update Quick Start in README.md

src/main/java/bio/overture/ego/grpc/interceptor/ApplicationAuthInterceptor.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/java/bio/overture/ego/utils/TypeUtils.java, src/test/java/bio/overture/ego/controller/AppJWTTest.java, src/test/java/bio/overture/ego/controller/UserSelfAssignApiKeyTest.java
=> ignore unknown jwt properties in jwt conversion
