overture-stack/ego

.circleci/config.yml
Maven failed tests during package step of deploy. Requiring it to skip tests will prevent this in the future. Tests are done separately so are not required in the deploy step.
https://github.com/overture-stack/ego/issues/31
=> [Ego-31] Skip Maven tests during deploy job

src/main/java/org/overture/ego/security/CorsFilter.java
Without this browsers reject API calls to ego. This specifies we accept the "token" header form cross domain requests.
https://github.com/overture-stack/ego/issues/19
=> [EGO-19] Allow "token" header in CorsFilter

src/main/java/org/overture/ego/model/entity/Application.java, src/main/java/org/overture/ego/model/entity/Group.java, src/main/java/org/overture/ego/model/entity/User.java
Make LazyCollection FALSE for all Entity Relations. These were throwing LazyInitialization exceptions when populating the responses to the GET services.
=> Fix LazyInitializationException

src/main/java/org/overture/ego/model/enums/UserRole.java, src/main/java/org/overture/ego/model/enums/UserStatus.java, src/main/java/org/overture/ego/service/UserService.java, src/main/java/org/overture/ego/token/TokenService.java, src/main/resources/application.yml
Demo server will allow all user's to log in and no user data to be persisted.
This is a repeat of work done in #20 but updated to work with the JPA refactor.
Enums are added back in, UserStatus now includes all 4 values permittable by the DB schema.
https://github.com/overture-stack/ego/issues/19
=> [Ego-19] Demo Config Flag to get Demo User on Login

src/main/java/org/overture/ego/model/entity/Application.java, src/main/java/org/overture/ego/model/entity/Group.java, src/main/java/org/overture/ego/model/entity/User.java
StackOverflowExceptions due to infinite loop was occuring for toString calls on Entities that had a relation to another entity. This was due to the default Lombok toString method which would print the value of all members. Due to relations, this caused infinite loops.
The solution is to exclude relations from Lombok's toString. The @ToString annotation allows specific fields to be excluded, fixing the infinite ToString loop.
=> Fix StackOverflowError for Users with Groups/Apps

src/main/java/org/overture/ego/reactor/events/UserEvents.java, src/main/java/org/overture/ego/reactor/receiver/UserReceiver.java, src/main/java/org/overture/ego/service/UserService.java, src/main/java/org/overture/ego/token/TokenService.java
Addresses two problems:
1. Event name wasn't unique, was reporting as "UPDATE". By adding the class name to the event identifier there won't be confusion between different update events.
2. The EventBus would break on dispatch of an event if the notify event had a different Object type than one of its subscribers. Some testing showed that this would prevent events with the matching data type from receiving the event - stopped dispatch completely. Careful coding would ensure all events had a data type to match the consumers, but this but the safer way to handle it is to make all Consumers of type Event<?> so that they will accept all Event payloads, and then to make the consumer explicitly cast the payload to the type they expect.
Now that the consumers are safe to receive all Events, we …
=> Refactor User Event and Receiver

README.md, docker-compose.yml
Adds postgres to the compose file so that a full ego deployment can be generated with a single `docker-compose up`.
=> Add postgres to compose for fully deployable setup

.circleci/config.yml, Dockerfile.prod
This Dockerfile.prod is created for deploying on Kubernetes (https://github.com/overture-stack/roadmap/issues/13).
- Its size is 225 MB (122 MB compressed) comparing to 1.11GB (497 Mb compressed) of current Dockerfile.
- The production docker image does not rely on `run.sh`. All spring configurations will be passed as environment variables(https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html).
- This docker image will be used by helm chart https://github.com/overture-stack/charts/tree/master/ego
=> Add production dockerfile

src/main/java/bio/overture/ego/security/OAuth2ClientResources.java
If ego is behind a proxy, it will not figure out the redirect uri directly. In this case, we need to hard code pre established redirect url.
=> Use pre established redirect url

src/main/java/bio/overture/ego/controller/AuthController.java
Ego itself should be as stateless as possible. ego-token endpoint should be accessed only once to make it more like OAuth flow. It's the client's responsibility to store the JWT token.
=> Ego token should only be accessed once

src/main/java/bio/overture/ego/controller/UserController.java, src/main/java/bio/overture/ego/model/dto/UpdateUserRequest.java, src/main/java/bio/overture/ego/model/entity/Application.java, src/main/java/bio/overture/ego/model/entity/User.java, src/main/java/bio/overture/ego/model/enums/JavaFields.java, src/main/java/bio/overture/ego/model/join/UserApplication.java, src/main/java/bio/overture/ego/model/join/UserApplicationId.java, src/main/java/bio/overture/ego/repository/queryspecification/ApplicationSpecification.java, src/main/java/bio/overture/ego/repository/queryspecification/UserSpecification.java, src/main/java/bio/overture/ego/repository/queryspecification/builder/AbstractSpecificationBuilder.java, src/main/java/bio/overture/ego/repository/queryspecification/builder/ApplicationSpecificationBuilder.java, src/main/java/bio/overture/ego/repository/queryspecification/builder/UserSpecificationBuilder.java, src/main/java/bio/overture/ego/service/AbstractBaseService.java, src/main/java/bio/overture/ego/service/ApplicationService.java, src/main/java/bio/overture/ego/service/BaseService.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/java/bio/overture/ego/service/UserService.java, src/main/java/bio/overture/ego/token/user/UserTokenClaims.java, src/main/java/bio/overture/ego/utils/Converters.java, src/main/resources/application.yml, src/test/java/bio/overture/ego/controller/AbstractControllerTest.java, src/test/java/bio/overture/ego/controller/ApplicationControllerTest.java, src/test/java/bio/overture/ego/controller/TokensOnUserAndPolicyDeletes.java, src/test/java/bio/overture/ego/controller/UserControllerTest.java, src/test/java/bio/overture/ego/service/ApplicationServiceTest.java, src/test/java/bio/overture/ego/service/UserServiceTest.java
Related to #330 
- Removed `@ManyToMany` and replaced with 2 `@OneToMany` with a join entity (`UserApplications`)
- Removed `lastLogin` from `UpdateUserRequest`. The `lastLogin` field should only be updated by the application, not by the user agent
- Removed useless jpa annotation arguments (refer to this [link](https://thoughts-on-java.org/hibernate-tips-whats-the-difference-between-column-nullable-false-and-notnull/))
- Add 36 User Controller tests
=> Ego 330 convert user application

src/main/java/bio/overture/ego/service/ApplicationService.java
Removed the logging code that printed the application token. Now only the clientId will print.
=> Removed logs that prints application token.

src/main/java/bio/overture/ego/config/ServerConfig.java, src/main/java/bio/overture/ego/controller/TokenController.java, src/test/java/bio/overture/ego/controller/TokenControllerTest.java, src/test/java/bio/overture/ego/controller/UserSelfAssignTokenTest.java, src/test/java/bio/overture/ego/utils/EntityGenerator.java
- Admin Users **CAN** create Access Tokens on behalf of other users (JWT Bearer)
- Admin Application **CAN** create Access Tokens on behalf of users (JWT Bearer ***OR*** Basic Auth)
- Non-Admin Users **CAN** create Access Tokens for themselves (JWT Bearer)
- Non-Admin Users **CANNOT** create Access Tokens on behalf of others
- Non-Admin Applications **CANNOT** create Access Tokens on behalf of others
- Auth check added to `POST /o/token` controller as described above.
- Unit Tests to validate behavior as described above
- Updated EntityGenerator to be able to create regular users in addition to admin users
- Update broken test that was previously returning 500 but with changes now returns 403
=> Token Creation self service

src/main/java/bio/overture/ego/model/entity/User.java, src/main/java/bio/overture/ego/token/user/UserTokenClaims.java, src/test/java/bio/overture/ego/token/JwtTest.java
Implementation for: https://github.com/overture-stack/ego/issues/390
Follows spec here: https://wiki.oicr.on.ca/display/icgcargotech/JWT+Specification
- Removed scopes from root of JWT Token Claims
- JSON Ignored the permissions so they don't show up in user info of claims
- Added getter for Group IDs for JSON Serialization of JWT
- Added Unit test of functionality
=> JWT Spec implementation and cleanup

pom.xml, src/main/resources/bootstrap-token.properties
Turns out when we jumped to JDK11 we broke the spring cloud config dependency but since we for the most part were not using it until now, we have not noticed.
This PR fixes that.
=> updates dependencies for jdk11 and vault

src/main/java/bio/overture/ego/event/token/CleanupTokenListener.java, src/main/java/bio/overture/ego/service/GroupService.java, src/main/resources/flyway/sql/V1_14__indices.sql
This fixes a performance issue related to how tokens were checked/cleaned up. Previously if a user was added to a group, the code would re-verify the tokens for every user in the group which is expensive. 
Also includes database indexes to speed up certain common joins.  
**Previous runtime of Daco2Ego:** Killed after 2+ hours
**New runtime of Daco2Ego:** 16 minutes
#364
=> Database indices and perf fix to group code

README.md, src/main/java/bio/overture/ego/security/CorsFilter.java, src/main/java/bio/overture/ego/security/OAuth2ClientResources.java, src/main/java/bio/overture/ego/security/OAuth2SsoFilter.java, src/main/java/bio/overture/ego/utils/Redirects.java, src/test/java/bio/overture/ego/utils/RedirectsTest.java
Provides support for clients to provide a redirect URI as a query param `redirect_uri`.  Applications should register a comma-delimited list of redirect URIs in the redirect uri fields. Redirect URIs just have to match the same authority (domain and port) and can be of dynamic path. If no redirect URI is present, the first valid URI from the list is used verbatim. 
- new query param `redirect_uri` added to login flow
- persistence of redirection to session nonce
- CORS validation with redirect uri 
- Utility class `Redirects` for correctly matching a redirect uri and verifying validity
- Unit tests
- Removed unused badges from README
=> Allows clients to specify redirect_uri query param.

src/main/java/bio/overture/ego/controller/PolicyController.java, src/main/java/bio/overture/ego/model/entity/AbstractPermission.java, src/main/java/bio/overture/ego/model/entity/UserPermission.java, src/main/java/bio/overture/ego/repository/queryspecification/SimpleCriteriaBuilder.java, src/main/java/bio/overture/ego/repository/queryspecification/UserPermissionSpecification.java, src/main/java/bio/overture/ego/service/AbstractPermissionService.java, src/main/java/bio/overture/ego/service/UserPermissionService.java, src/main/resources/application.yml, src/test/java/bio/overture/ego/controller/AbstractPermissionControllerTest.java, src/test/java/bio/overture/ego/controller/UserPermissionControllerTest.java
Query now correctly generates non-redundant joins, and is joining on the correct entities
Also added a generic SimpleCriteriaBuilder utility.
There is a test called `addPermissionsToOwner_Unique_Success__ROB`, that was used to trigger the find vs listing feature of /policies/{}/users
To inspect the SQL queries, uncomment the appropriate lines in the application.yml and run the above test
=> 448 Fixed UserPermissions queries for /policy/{}/users endpoint

src/main/resources/flyway/sql/V1_15_5__remove_duplicate_joins.sql
We missed removing the duplicate rows for the add unique constraint migration. This is required for that one to run correctly.
=> migration to remove duplicate join table rows

Dockerfile
This allows for more idiomatic custom run-time command. 
In IHCC, we want to override the run-time command to read some secret and translate back to env var before starting the app.
=> 🐳 updates Dockerfile to use CMD instead of ENTRYPOINT

src/main/java/bio/overture/ego/model/dto/PolicyRequest.java, src/main/java/bio/overture/ego/model/dto/Scope.java, src/main/java/bio/overture/ego/model/entity/Policy.java, src/main/java/bio/overture/ego/service/ApplicationService.java, src/main/java/bio/overture/ego/service/UserService.java, src/test/java/bio/overture/ego/controller/AbstractResolvablePermissionControllerTest.java, src/test/java/bio/overture/ego/controller/ApiKeyControllerTest.java, src/test/java/bio/overture/ego/controller/AppJWTTest.java, src/test/java/bio/overture/ego/controller/PolicyControllerTest.java, src/test/java/bio/overture/ego/controller/TokensOnPermissionsChangeTest.java, src/test/java/bio/overture/ego/controller/UpdateTokenTest.java
Also enforces Policy name characters to be {alphanumeric, _, -}
Required for 3.3.x to be deployed as this was blocking application authentication.
=> Provide Default Scope if none available

src/main/java/bio/overture/ego/service/ApiKeyStoreService.java, src/main/java/bio/overture/ego/service/TokenService.java, src/main/resources/application.yml, src/test/java/bio/overture/ego/controller/AppJWTTest.java, src/test/java/bio/overture/ego/controller/UpdateTokenTest.java, src/test/java/selenium/LoadAdminUITest.java
- User JWT duration is configured via `jwt.user.durationMs`
- App JWT duration is configured via `jwt.app.durationMs`
- Ran google code formatter
- Improved code quality and eliminated many warning from `TokenService.java`
- Removed deprecation annotation as non-deprecated method throws `NotImplemented`
=> Different durations for app and user jwts.

pom.xml, src/main/java/bio/overture/ego/config/LoginNonceProperties.java, src/main/java/bio/overture/ego/config/SecureServerConfig.java, src/main/java/bio/overture/ego/config/SessionConfig.java, src/main/resources/application.yml
Allows the configuring of the `DefaultCookieSerializer` as part of `spring-session`.  This will allow us to set the `SameSite` attribute to `None` allowing for cross origin logins.
With sensible defaults:
```yaml
login:
nonce:
name: LOGIN_NONCE
sameSite: none
secure: true
maxAge: 120
domainPattern: ^.+?\.(\w+\.[a-z]+)$
```
A `maxAge` of `-1` will tell the browser to delete the cookie on next close. 
Should be transparent to the UI as these are `HttpOnly` cookies.
Example of new cookie in action:
```
Set-Cookie: LOGIN_NONCE=MWMxOTE2MWUtYjU5NS00ZGNkLWE5ZmItMDgzM2U4OTRkNDEy; Max-Age=120; Expires=Wed, 16 Dec 2020 12:55:43 -0500; Path=/; Secure; HttpOnly; SameSite=none
```
- `SameSite: None` is only allowed when cookie is `Secure`. This means HTTPS only. Otherwise the browser will block the …
=> SameSite cookie fix. Allows session cookie to be configured.

pom.xml
- Removes the new private spring maven repos
- Updates gRPC dependency as the older version is not in maven central.
=> Removes the now private spring-repos. Updates grpc.

Jenkinsfile
Ego is ready to use chart 3.0.0, already deployed in the env and this PR is for future CDs
=> use chart 3.0.0

src/main/java/bio/overture/ego/controller/UserController.java, src/main/java/bio/overture/ego/model/enums/Fields.java, src/main/java/bio/overture/ego/repository/queryspecification/UserSpecification.java, src/test/java/bio/overture/ego/controller/UserControllerTest.java
Adds email and providerType fields to SearchFilters list. This will fix a [request](https://github.com/icgc-argo/Daco2Ego/blob/master/python/ego_client.py#L89) for users in Daco2Ego that wasn't filtering correctly, and allow filtering on `providerType`.
Also adds providerType to User query spec as a nice to have.
=> 🐛 Add email, providerType to allowed search filters

docker-compose-all.yml, src/main/java/bio/overture/ego/security/OAuth2RequestResolver.java, src/test/java/bio/overture/ego/controller/RefreshTokenTest.java
#634 
fix OAuth2RequestResolver to only check on request that match the oauth2 login flow.
=> fix issue #634 redirect_uri lost
